name: covidapp
description: Covid 19 upadte app built with flutter updates users enabled with dark mode 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.6 
  dio: ^4.0.6  
  adaptive_theme: ^3.1.1 
  share_plus: ^4.5.3 
  pie_chart: ^5.3.2  
  flutter_riverpod: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

 
  uses-material-design: true
  assets:
    - images/
  fonts:
     - family: Poppins
       fonts:
          - asset: fonts/Poppins/Poppins-Medium.ttf
          - asset: fonts/Poppins/Poppins-Regular.ttf

  